const vocabularyData = [
    { word: "天下大势", pinyin: "tiān xià dà shì", defZh: "天下局势发展的总体趋势和走向。", defEn: "The general trend of the world", defBm: "Keadaan umum dunia / Aliran semasa", example: "他看清了天下大势，决定顺应民心，举兵起义。" },
    { word: "荒淫昏庸", pinyin: "huāng yín hūn yōng", defZh: "生活放荡沉迷酒色，又愚蠢无能。", defEn: "Licentious and incompetent", defBm: "Bebas dan bodoh (bagi pemerintah)", example: "这位皇帝荒淫昏庸，不理朝政，国家日渐衰落。" },
    { word: "把持朝纲", pinyin: "bǎ chí cháo gāng", defZh: "掌控朝廷的政权和法令。", defEn: "Control the court and government", defBm: "Menguasai istana dan pemerintahan", example: "奸臣当道，把持朝纲，百姓苦不堪言。" },
    { word: "政治腐败", pinyin: "zhèng zhì fǔ bài", defZh: "国家政权被腐蚀，官员贪赃枉法。", defEn: "Political corruption", defBm: "Rasuah politik", example: "政治腐败导致国库空虚，民不聊生。" },
    { word: "民怨四起", pinyin: "mín yuàn sì qǐ", defZh: "百姓的怨恨从四面八方涌现出来。", defEn: "Public resentment arises everywhere", defBm: "Kemarahan rakyat timbul di mana-mana", example: "苛捐杂税繁重，导致民怨四起，各地纷纷起义。" },
    { word: "波涛", pinyin: "bō tāo", defZh: "大波浪，比喻动荡不安的局势。", defEn: "Great waves / Billows", defBm: "Ombak besar", example: "天下大势如同波涛汹涌，充满了变数。" },
    { word: "覆灭", pinyin: "fù miè", defZh: "全部被消灭、彻底毁灭。", defEn: "Destruction / Annihilation", defBm: "Kemusnahan / Kehancuran", example: "这个腐败的政权最终走向了覆灭。" },
    { word: "乘机起事", pinyin: "chéng jī qǐ shì", defZh: "利用有利的机会发动起义或起兵。", defEn: "Seize the opportunity to rise up", defBm: "Mengambil kesempatan untuk bangkit", example: "他乘机起事，召集义士，准备推翻暴政。" },
    { word: "自称", pinyin: "zì chēng", defZh: "自己称呼自己为（某名号）。", defEn: "Call oneself / Claim to be", defBm: "Menggelar diri sendiri sebagai", example: "他自称是汉室宗亲，以此吸引百姓的支持。" },
    { word: "呼风唤雨", pinyin: "hū fēng huàn yǔ", defZh: "比喻拥有巨大的权力和号召力。", defEn: "Summon wind and rain (have great power)", defBm: "Menyeru angin dan hujan (berkuasa besar)", example: "在乱世之中，他如同呼风唤雨般聚集了上万义军。" },
    { word: "治病解危", pinyin: "zhì bìng jiě wēi", defZh: "治疗疾病，解除危难。", defEn: "Cure diseases and relieve crises", defBm: "Menyembuhkan penyakit dan menyelesaikan krisis", example: "他立志行医，治病解危，深得百姓爱戴。" },
    { word: "供奉", pinyin: "gòng fèng", defZh: "用祭品或香火来敬奉神明或祖先。", defEn: "Enshrine and worship", defBm: "Memuja / Menyembah", example: "百姓在祠堂里供奉着先祖的牌位，祈求平安。" },
    { word: "时机成熟", pinyin: "shí jī chéng shú", defZh: "做事的条件已经具备，时机到了。", defEn: "The time is ripe", defBm: "Masa yang sesuai / Tiba masanya", example: "等到时机成熟，他们便会举兵起义。" },
    { word: "造反", pinyin: "zào fǎn", defZh: "发动叛乱，反抗朝廷的统治。", defEn: "Rebel / Revolt", defBm: "Memberontak", example: "百姓忍受不了压迫，纷纷起来造反。" },
    { word: "声势浩大", pinyin: "shēng shì hào dà", defZh: "声威和气势非常宏大。", defEn: "Great momentum / Grand scale", defBm: "Pengaruh yang besar / Kekuatan yang hebat", example: "义军声势浩大，令朝廷感到十分震惊。" },
    { word: "所向披靡", pinyin: "suǒ xiàng pī mǐ", defZh: "力量强大，所到之处敌人纷纷败退。", defEn: "Invincible / Ever-victorious", defBm: "Tidak terkalahkan / Sentiasa menang", example: "这支军队训练有素，所向披靡，连战连胜。" },
    { word: "征讨", pinyin: "zhēng tǎo", defZh: "出兵讨伐、平定叛乱或敌人。", defEn: "Go on a punitive expedition", defBm: "Melancarkan kempen ketenteraan", example: "朝廷命他率兵征讨叛军，恢复地方安定。" },
    { word: "榜文", pinyin: "bǎng wén", defZh: "古代官府张贴的告示或通告。", defEn: "Proclamation / Official notice", defBm: "Notis rasmi / Pengumuman", example: "城门上贴着一张榜文，招募有志之士从军报国。" },
    { word: "宽和", pinyin: "kuān hé", defZh: "待人宽厚、温和，不苛刻。", defEn: "Gentle and lenient", defBm: "Lemah lembut / Bertolak ansur", example: "他为人宽和，深得部下和百姓的爱戴。" },
    { word: "胸怀大志", pinyin: "xiōng huái dà zhì", defZh: "心中怀有远大的志向和抱负。", defEn: "Have high aspirations", defBm: "Mempunyai cita-cita tinggi", example: "他虽然出身贫寒，但胸怀大志，不甘于平凡。" },
    { word: "一事无成", pinyin: "yí shì wú chéng", defZh: "什么事情都没做成，毫无成就。", defEn: "Achieve nothing", defBm: "Tidak mencapai apa-apa kejayaan", example: "年过半百却一事无成，他心中充满了感慨。" },
    { word: "感慨万分", pinyin: "gǎn kǎi wàn fēn", defZh: "内心充满深深的感触和叹息。", defEn: "Filled with deep emotion", defBm: "Sangat terharu / Penuh emosi", example: "回想当年的雄心壮志，如今却一事无成，他不禁感慨万分。" },
    { word: "络腮胡", pinyin: "luò sāi hú", defZh: "长满两颊和下巴的胡子。", defEn: "Full beard", defBm: "Janggut penuh (di pipi dan dagu)", example: "他留着一脸浓密的络腮胡，看起来十分威武。" },
    { word: "宗室", pinyin: "zōng shì", defZh: "皇室的家族成员。", defEn: "Royal family / Clansmen", defBm: "Kerabat diraja", example: "他是汉室宗室，对朝政有着深厚的情感。" },
    { word: "相貌堂堂", pinyin: "xiàng mào táng táng", defZh: "形容人的外表端正、威严、有气度。", defEn: "Dignified appearance", defBm: "Rupa paras yang tampan dan gagah", example: "他相貌堂堂，器宇轩昂，一看就是人中豪杰。" },
    { word: "威风凛凛", pinyin: "wēi fēng lǐn lǐn", defZh: "气势威严，令人敬畏的样子。", defEn: "Majestic / Awe-inspiring", defBm: "Hebat dan menggerunkan", example: "他身穿铠甲，手持长枪，威风凛凛地站在阵前。" },
    { word: "应征", pinyin: "yìng zhēng", defZh: "响应招募，报名参加。", defEn: "Respond to a call for recruits", defBm: "Menyahut seruan (untuk menyertai tentera)", example: "他看到榜文后，毅然应征入伍，报效国家。" },
    { word: "商议", pinyin: "shāng yì", defZh: "一起讨论、商量事情。", defEn: "Discuss / Consult", defBm: "Berbincang", example: "几位好友围坐一起，商议救国扶危的大计。" },
    { word: "背义忘恩", pinyin: "bèi yì wàng ēn", defZh: "忘记别人对自己的恩情，做出不义的事。", defEn: "Ungrateful / Betrayal", defBm: "Tidak mengenang budi / Mengkhianati", example: "他背义忘恩，背叛了曾经帮助过他的结义兄弟。" },
    { word: "投靠", pinyin: "tóu kào", defZh: "去投奔某人，寻求庇护或依靠。", defEn: "Seek refuge / Rely on", defBm: "Menumpang / Meminta perlindungan", example: "他走投无路，只得投靠远方的朋友。" },
    { word: "屡建战功", pinyin: "lǚ jiàn zhàn gōng", defZh: "多次在战场上立下功劳。", defEn: "Repeatedly achieve military exploits", defBm: "Kerap mencapai kejayaan tentera", example: "他英勇善战，屡建战功，被封为大将军。" },
    { word: "名声渐大", pinyin: "míng shēng jiàn dà", defZh: "声望和名气逐渐变大。", defEn: "Gradually become famous", defBm: "Nama semakin terkenal", example: "经过连年征战，他的名声渐大，天下皆知。" }
];

// 将数据暴露为全局变量
var allIdioms = vocabularyData;
