const vocabularyData = [
    { word: "安民", pinyin: "ān mín", defZh: "使人民安定，让百姓过上安稳的生活。", defEn: "Pacify the people / Bring peace", defBm: "Mententeramkan rakyat", example: "新上任的官员决心安民，改善百姓的生活。" },
    { word: "把持", pinyin: "bǎ chí", defZh: "用权力或势力控制、掌握。", defEn: "Control / Dominate", defBm: "Mengawal / Menguasai", example: "朝中的奸臣把持朝政，导致国家日益衰败。" },
    { word: "百姓", pinyin: "bǎi xìng", defZh: "普通的人民、平民百姓。", defEn: "Common people / Citizens", defBm: "Rakyat", example: "战争爆发后，百姓流离失所，生活困苦。" },
    { word: "榜文", pinyin: "bǎng wén", defZh: "古代官府张贴的告示或通告。", defEn: "Proclamation / Official notice", defBm: "Notis rasmi / Pengumuman", example: "城门口贴着一张榜文，招募有志之士投军。" },
    { word: "背义忘恩", pinyin: "bèi yì wàng ēn", defZh: "忘记别人对自己的恩情，做出不义的事。", defEn: "Ungrateful / Betrayal", defBm: "Tidak mengenang budi / Mengkhianati", example: "他背义忘恩，背叛了曾经帮助过他的朋友。" },
    { word: "本地", pinyin: "běn dì", defZh: "当地人居住的这个地方，附近一带。", defEn: "Local", defBm: "Tempatan", example: "这家店的老板是本地人，对这里非常熟悉。" },
    { word: "镔铁", pinyin: "bīn tiě", defZh: "一种质地精良、坚韧的铁，用于打造兵器。", defEn: "Fine iron / Wrought iron", defBm: "Besi tempa / Besi berkualiti", example: "他用镔铁打造了一把锋利无比的大刀。" },
    { word: "波涛", pinyin: "bō tāo", defZh: "大波浪，比喻局势动荡或气势宏大。", defEn: "Great waves / Billows", defBm: "Ombak besar", example: "海面上波涛汹涌，船只不敢出海航行。" },
    { word: "不禁", pinyin: "bù jīn", defZh: "不由自主地、忍不住（某种情绪或动作）。", defEn: "Can't help (doing sth)", defBm: "Tidak dapat menahan (perasaan)", example: "听到这个消息，他不禁流下了眼泪。" },
    { word: "部众", pinyin: "bù zhòng", defZh: "部下、随从或所属的群众。", defEn: "Troops / Followers", defBm: "Pasukan / Pengikut tentera", example: "他率领部众，奋勇杀敌，立下了赫赫战功。" },
    { word: "长叹", pinyin: "cháng tàn", defZh: "深深地叹息，表示无奈或感慨。", defEn: "Sigh deeply", defBm: "Mengeluh panjang", example: "他望着破碎的家园，不禁长叹一声。" },
    { word: "朝纲", pinyin: "cháo gāng", defZh: "朝廷的纲纪、法令和制度。", defEn: "Court discipline / Laws", defBm: "Peraturan istana / Undang-undang negara", example: "皇帝整顿朝纲，严惩贪官污吏。" },
    { word: "朝廷", pinyin: "cháo tíng", defZh: "古代皇帝处理国事的地方，也指中央政府。", defEn: "Imperial court", defBm: "Istana (kerajaan pada zaman dahulu)", example: "朝廷下令，各地官员要尽力安抚百姓。" },
    { word: "趁机", pinyin: "chèn jī", defZh: "利用有利的时机或机会。", defEn: "Seize the opportunity", defBm: "Mengambil kesempatan", example: "他趁敌人不备，趁机发动了突袭。" },
    { word: "成熟", pinyin: "chéng shú", defZh: "事物发展到完善的阶段，或人思想稳重。", defEn: "Mature / Ripe", defBm: "Matang / Masak", example: "经过多年的历练，他的思想已经变得成熟稳重。" },
    { word: "出发", pinyin: "chū fā", defZh: "启程、动身前往目的地。", defEn: "Set out / Depart", defBm: "Bertolak", example: "天还没亮，他们就出发赶往京城了。" },
    { word: "出力", pinyin: "chū lì", defZh: "付出力量、尽自己的能力去做事。", defEn: "Put forth effort / Contribute", defBm: "Menyumbang tenaga / Berusaha", example: "为了保卫家园，每个人都愿意出力。" },
    { word: "垂肩", pinyin: "chuí jiān", defZh: "（头发或物体）垂落到肩膀。", defEn: "Hang down to the shoulders", defBm: "Jatuh mencecah bahu", example: "他有一头乌黑的长发，垂肩而下。" },
    { word: "从军", pinyin: "cóng jūn", defZh: "参加军队、入伍当兵。", defEn: "Join the army", defBm: "Menyertai tentera", example: "他年纪轻轻就决定从军，报效国家。" },
    { word: "粗犷", pinyin: "cū guǎng", defZh: "形容性格豪爽、不拘小节，或声音粗豪。", defEn: "Rough / Rugged", defBm: "Kasar / Gagah", example: "他外表粗犷，但内心其实非常细腻。" },
    { word: "打造", pinyin: "dǎ zào", defZh: "锻造、制造（多指金属器具）。", defEn: "Forge / Create", defBm: "Menempa / Membuat", example: "铁匠打造了一把锋利的宝剑。" },
    { word: "丹凤", pinyin: "dān fèng", defZh: "红色的凤凰，常形容人的眼睛细长而有神。", defEn: "Red phoenix (used to describe eyes)", defBm: "Burung cenderawasih (merujuk kepada bentuk mata)", example: "他生得一双丹凤眼，炯炯有神。" },
    { word: "大乱", pinyin: "dà luàn", defZh: "社会动荡不安，秩序混乱的局面。", defEn: "Great chaos / Upheaval", defBm: "Kekacauan besar", example: "天下大乱，各地英雄纷纷起兵。" },
    { word: "大势", pinyin: "dà shì", defZh: "事情发展的总体趋势或大局。", defEn: "General trend / Situation", defBm: "Keadaan umum / Aliran semasa", example: "他看清了大势，决定顺应民心。" },
    { word: "大丈夫", pinyin: "dà zhàng fū", defZh: "有志气、有作为的男子汉。", defEn: "True man / Manly man", defBm: "Lelaki sejati", example: "大丈夫顶天立地，应当有所作为。" },
    { word: "帝王", pinyin: "dì wáng", defZh: "古代国家的最高统治者，即皇帝。", defEn: "Emperor / Monarch", defBm: "Maharaja", example: "帝王治国，应以百姓的福祉为重。" },
    { word: "多次", pinyin: "duō cì", defZh: "好多次、许多次。", defEn: "Many times", defBm: "Berkali-kali", example: "他多次上书朝廷，提出改革的建议。" },
    { word: "夺取", pinyin: "duó qǔ", defZh: "用武力或手段强行取得。", defEn: "Seize / Capture", defBm: "Merampas / Menawan", example: "敌军企图夺取这座城池，但失败了。" },
    { word: "腐败", pinyin: "fǔ bài", defZh: "（制度、机构等）腐烂、堕落，贪赃枉法。", defEn: "Corrupt / Rotten", defBm: "Rasuah / Reput", example: "朝廷腐败，百姓怨声载道。" },
    { word: "覆灭", pinyin: "fù miè", defZh: "全部被消灭、毁灭。", defEn: "Destruction / Annihilation", defBm: "Kemusnahan / Kehancuran", example: "这个腐败的政权最终走向了覆灭。" },
    { word: "感慨万分", pinyin: "gǎn kǎi wàn fēn", defZh: "内心充满深深的感触和叹息。", defEn: "Filled with deep emotion", defBm: "Sangat terharu / Penuh emosi", example: "他回想起当年的往事，不禁感慨万分。" },
    { word: "跟从", pinyin: "gēn cóng", defZh: "跟随、追随（某人）。", defEn: "Follow", defBm: "Mengikut", example: "他决定跟从刘备，一起闯荡天下。" },
    { word: "共图大事", pinyin: "gòng tú dà shì", defZh: "一起谋划、成就伟大的事业。", defEn: "Plan great undertakings together", defBm: "Merancang perkara besar bersama", example: "三人结拜为兄弟，发誓共图大事。" },
    { word: "供奉", pinyin: "gòng fèng", defZh: "用祭品或香火来敬奉神明或祖先。", defEn: "Enshrine and worship", defBm: "Memuja / Menyembah", example: "他们在祠堂里供奉着先祖的牌位。" },
    { word: "过膝", pinyin: "guò xī", defZh: "（手臂或某物）长到超过膝盖。", defEn: "Past the knees", defBm: "Melepasi lutut", example: "他的手臂很长，双手过膝。" },
    { word: "豪杰", pinyin: "háo jié", defZh: "才能出众、英勇豪迈的人。", defEn: "Hero / Outstanding person", defBm: "Wira / Orang yang gagah berani", example: "天下的豪杰纷纷响应号召，共聚一堂。" },
    { word: "浩大", pinyin: "hào dà", defZh: "规模、气势等非常宏大。", defEn: "Huge / Vast", defBm: "Sangat besar / Hebat", example: "这场战役的规模浩大，涉及数十万士兵。" },
    { word: "恨不能", pinyin: "hèn bù néng", defZh: "非常希望（做某事），恨不得。", defEn: "Wish one could / Itching to", defBm: "Sangat berharap dapat", example: "他恨不能立刻飞到前线去支援。" },
    { word: "洪亮", pinyin: "hóng liàng", defZh: "（声音）大而响亮、清晰。", defEn: "Loud and clear", defBm: "Lantang dan jelas (suara)", example: "他说话声音洪亮，全场人都听得清清楚楚。" },
    { word: "呼风唤雨", pinyin: "hū fēng huàn yǔ", defZh: "比喻拥有巨大的力量和权威。", defEn: "Summon wind and rain (control nature)", defBm: "Menyeru angin dan hujan (berkuasa besar)", example: "在小说中，神仙可以呼风唤雨。" },
    { word: "荒淫", pinyin: "huāng yín", defZh: "生活放荡、沉迷酒色，没有节制。", defEn: "Licentious / Dissolute", defBm: "Kelakuan buruk / Bebas (seksual)", example: "这位皇帝昏庸荒淫，导致国家走向灭亡。" },
    { word: "化解", pinyin: "huà jiě", defZh: "将矛盾、怨恨等消除掉。", defEn: "Resolve / Dissolve", defBm: "Menyelesaikan / Menghuraikan", example: "他出面调解，成功化解了双方的矛盾。" },
    { word: "昏庸", pinyin: "hūn yōng", defZh: "（君主或官员）愚蠢、无能，不明事理。", defEn: "Faint and incompetent", defBm: "Bodoh / Tidak cekap (bagi pemerintah)", example: "昏庸的君主不理朝政，国家迟早会灭亡。" },
    { word: "急令", pinyin: "jí lìng", defZh: "紧急下达的命令。", defEn: "Urgently order", defBm: "Mengarahkan dengan segera", example: "朝廷急令各地将领率兵勤王。" },
    { word: "祭告", pinyin: "jì gào", defZh: "用祭品向神明或祖先禀告、祈祷。", defEn: "Offer sacrifices and pray", defBm: "Mempersembahkan korban dan berdoa", example: "他们燃香祭告天地，结为异姓兄弟。" },
    { word: "祭品", pinyin: "jì pǐn", defZh: "祭祀时供奉给神明或祖先的物品。", defEn: "Sacrificial offering", defBm: "Barang persembahan / Korban", example: "他们在桌上摆满了祭品，准备进行祭祀仪式。" },
    { word: "结拜", pinyin: "jié bài", defZh: "没有血缘关系的人结为兄弟或姐妹。", defEn: "Become sworn brothers", defBm: "Angkat sumpah saudara", example: "三人志同道合，决定在桃园结拜为兄弟。" },
    { word: "结交", pinyin: "jié jiāo", defZh: "与人相识、建立友谊关系。", defEn: "Make friends with", defBm: "Berkawan / Menjalin hubungan", example: "他喜欢结交天下豪杰，广交朋友。" },
    { word: "尽力", pinyin: "jìn lì", defZh: "尽自己最大的努力去做事。", defEn: "Do one's best", defBm: "Berusaha sedaya upaya", example: "他承诺一定会尽力帮助朋友度过难关。" },
    { word: "敬佩", pinyin: "jìng pèi", defZh: "敬重、佩服（某人）。", defEn: "Admire / Respect", defBm: "Kagum / Menghormati", example: "他的忠义精神令人敬佩。" },
    { word: "酒保", pinyin: "jiǔ bǎo", defZh: "古代酒店或酒馆里的伙计、服务员。", defEn: "Bartender / Waiter", defBm: "Pelayan kedai arak", example: "酒保端上一壶好酒，招待三位英雄。" },
    { word: "救国扶危", pinyin: "jiù guó fú wēi", defZh: "拯救国家，扶助危难中的百姓。", defEn: "Save the country and help those in danger", defBm: "Menyelamatkan negara dan membantu yang dalam bahaya", example: "他立下大志，要救国扶危，造福百姓。" },
    { word: "聚集", pinyin: "jù jí", defZh: "人、物等从四面八方汇集在一起。", defEn: "Gather / Assemble", defBm: "Berkumpul", example: "各地的义军纷纷聚集，准备联合讨伐敌人。" },
    { word: "铠甲", pinyin: "kǎi jiǎ", defZh: "古代士兵作战时穿的防护衣服。", defEn: "Armor", defBm: "Baju besi", example: "他穿上铠甲，手持长枪，准备上阵杀敌。" },
    { word: "可惜", pinyin: "kě xī", defZh: "表示惋惜、遗憾。", defEn: "What a pity", defBm: "Sayang sekali", example: "可惜他英年早逝，没能看到国家统一。" },
    { word: "宽和", pinyin: "kuān hé", defZh: "待人宽厚、温和，不苛刻。", defEn: "Gentle and lenient", defBm: "Lemah lembut / Bertolak ansur", example: "他为人宽和，深得部下和百姓的爱戴。" },
    { word: "良马", pinyin: "liáng mǎ", defZh: "好的马、骏马。", defEn: "Good horse / Steed", defBm: "Kuda yang baik", example: "他骑着一匹良马，日夜兼程赶路。" },
    { word: "路过", pinyin: "lù guò", defZh: "在途中经过某个地方。", defEn: "Pass by", defBm: "Singgah / Lalu di sesuatu tempat", example: "他路过桃园时，看到一片美丽的桃花。" },
    { word: "屡建战功", pinyin: "lǚ jiàn zhàn gōng", defZh: "多次在战场上立下功劳。", defEn: "Repeatedly achieve military exploits", defBm: "Kerap mencapai kejayaan tentera", example: "他勇猛善战，屡建战功，被封为大将军。" },
    { word: "络腮胡", pinyin: "luò sāi hú", defZh: "长满两颊和下巴的胡子。", defEn: "Full beard", defBm: "Janggut penuh (di pipi dan dagu)", example: "他留着浓密的络腮胡，看起来威武不凡。" },
    { word: "面色", pinyin: "miàn sè", defZh: "脸部的颜色，指气色或表情。", defEn: "Complexion", defBm: "Warna muka", example: "他面色凝重，似乎有什么心事。" },
    { word: "民怨", pinyin: "mín yuàn", defZh: "百姓的怨恨和不满。", defEn: "Public resentment", defBm: "Kemarahan rakyat", example: "苛捐杂税导致民怨沸腾，百姓苦不堪言。" },
    { word: "名声", pinyin: "míng shēng", defZh: "在社会上流传的评价和名誉。", defEn: "Reputation", defBm: "Reputasi / Nama baik", example: "他因忠义而名声远扬，天下皆知。" },
    { word: "募集", pinyin: "mù jí", defZh: "通过号召或筹集，聚集钱财或人才。", defEn: "Raise / Recruit", defBm: "Mengumpul / Merekrut", example: "他募集了一批义士，准备共商大事。" },
    { word: "年龄", pinyin: "nián líng", defZh: "一个人活了多少岁。", defEn: "Age", defBm: "Umur", example: "三人虽然年龄不同，但志趣相投，结为兄弟。" },
    { word: "贫穷", pinyin: "pín qióng", defZh: "家里很穷、没有财物。", defEn: "Poor / Impoverished", defBm: "Miskin", example: "他出身贫穷，但胸怀大志，不甘于平凡。" },
    { word: "齐声", pinyin: "qí shēng", defZh: "众人一起发出同样的声音。", defEn: "In chorus / Unison", defBm: "Bersuara serentak", example: "众人齐声高呼，表达内心的喜悦。" },
    { word: "起誓", pinyin: "qǐ shì", defZh: "庄严地发誓、立下誓言。", defEn: "Take an oath / Swear", defBm: "Bersumpah", example: "他起誓要为国尽忠，至死不渝。" },
    { word: "起事", pinyin: "qǐ shì", defZh: "发动起义或起兵反抗。", defEn: "Stage an uprising / Revolt", defBm: "Melancarkan pemberontakan", example: "各地英雄纷纷起事，反抗暴政。" },
    { word: "钱财", pinyin: "qián cái", defZh: "金钱和财物。", defEn: "Wealth / Money", defBm: "Harta benda / Wang", example: "他散尽家财，用来招募士兵。" },
    { word: "燃香", pinyin: "rán xiāng", defZh: "点燃香烛，用于祭祀或祈福。", defEn: "Burn incense", defBm: "Membakar colok / kemenyan", example: "他们在香案前燃香，虔诚地拜祭天地。" },
    { word: "商议", pinyin: "shāng yì", defZh: "一起讨论、商量事情。", defEn: "Discuss / Consult", defBm: "Berbincang", example: "三人围坐在一起，商议举兵的大事。" },
    { word: "声势", pinyin: "shēng shì", defZh: "名声和气势，指影响力。", defEn: "Momentum / Prestige", defBm: "Pengaruh / Kekuatan", example: "这支军队声势浩大，令敌人闻风丧胆。" },
    { word: "事业", pinyin: "shì yè", defZh: "人所从事的、有一定目标和规模的工作。", defEn: "Career / Undertaking", defBm: "Kerjaya / Usaha", example: "他立志要干一番惊天动地的事业。" },
    { word: "收拾", pinyin: "shōu shi", defZh: "整理、整顿，也指准备。", defEn: "Pack / Tidy up", defBm: "Mengemas", example: "他收拾好行装，准备出发。" },
    { word: "数量", pinyin: "shù liàng", defZh: "事物的多少、数目。", defEn: "Quantity / Amount", defBm: "Kuantiti / Bilangan", example: "敌军数量众多，但我方士气高昂。" },
    { word: "率领", pinyin: "shuài lǐng", defZh: "带领、引导（队伍或人群）。", defEn: "Lead / Command", defBm: "Memimpin / Mengetuai", example: "他率领三千精兵，直奔敌军大营。" },
    { word: "私造", pinyin: "sī zào", defZh: "私下、非法地制造（多指兵器等）。", defEn: "Illegally manufacture", defBm: "Membuat secara haram / rahsia", example: "朝廷严禁民间私造兵器。" },
    { word: "所向披靡", pinyin: "suǒ xiàng pī mǐ", defZh: "力量强大，所到之处敌人纷纷败退。", defEn: "Invincible / Ever-victorious", defBm: "Tidak terkalahkan / Sentiasa menang", example: "他的军队训练有素，所向披靡，连战连胜。" },
    { word: "太监", pinyin: "tài jiàn", defZh: "古代皇宫中服侍皇帝和皇室的男性官员。", defEn: "Eunuch", defBm: "Sida-sida", example: "太监奉皇帝之命，传达朝廷的旨意。" },
    { word: "太守", pinyin: "tài shǒu", defZh: "古代郡一级的最高行政长官。", defEn: "Prefect / Governor", defBm: "Gabenor / Pegawai daerah", example: "太守听闻敌军来犯，立即下令加强城防。" },
    { word: "天下", pinyin: "tiān xià", defZh: "整个国家或世界，也指全国的人。", defEn: "The world (under heaven)", defBm: "Dunia / Seluruh negara", example: "他胸怀天下，一心为民造福。" },
    { word: "天书", pinyin: "tiān shū", defZh: "神秘难懂的书，或天命之书。", defEn: "Heavenly book / Divine book", defBm: "Buku dari syurga / Kitab suci", example: "传说中，有缘人才能读懂天书的奥秘。" },
    { word: "同心协力", pinyin: "tóng xīn xié lì", defZh: "心往一处想，劲往一处使。", defEn: "Work together with one heart", defBm: "Bekerjasama sehati sejiwa", example: "只有大家同心协力，才能成就大业。" },
    { word: "痛饮", pinyin: "tòng yǐn", defZh: "尽情痛快地喝酒。", defEn: "Drink heartily", defBm: "Minum sepuas-puasnya", example: "兄弟们欢聚一堂，痛饮庆祝结义。" },
    { word: "投靠", pinyin: "tóu kào", defZh: "去投奔某人，投到其门下寻求庇护。", defEn: "Seek refuge / Rely on", defBm: "Menumpang / Meminta perlindungan", example: "他走投无路，只得投靠远方的亲戚。" },
    { word: "徒众", pinyin: "tú zhòng", defZh: "徒弟、学生或跟随者的总称。", defEn: "Followers / Disciples", defBm: "Pengikut", example: "他在各地广收徒众，传授武艺。" },
    { word: "涂脂", pinyin: "tú zhī", defZh: "涂抹胭脂或口红，指打扮。", defEn: "Apply rouge or lipstick", defBm: "Memakai gincu", example: "古代女子喜欢涂脂抹粉，打扮自己。" },
    { word: "玩耍", pinyin: "wán shuǎ", defZh: "做游戏、玩乐。", defEn: "Play", defBm: "Bermain", example: "童年的时光总是无忧无虑，充满玩耍的乐趣。" },
    { word: "威风凛凛", pinyin: "wēi fēng lǐn lǐn", defZh: "气势威严，令人敬畏的样子。", defEn: "Majestic / Awe-inspiring", defBm: "Hebat dan menggerunkan", example: "他身穿铠甲，手持宝剑，威风凛凛地站在城楼上。" },
    { word: "维持", pinyin: "wéi chí", defZh: "保持、使某种状态延续下去。", defEn: "Maintain / Keep", defBm: "Mengekalkan / Menyara (hidup)", example: "他靠卖草鞋为生，勉强维持生计。" },
    { word: "危险", pinyin: "wēi xiǎn", defZh: "有遭受损害或失败的可能。", defEn: "Danger / Dangerous", defBm: "Bahaya", example: "战场上的局势十分危险，必须万分小心。" },
    { word: "卧蚕", pinyin: "wò cán", defZh: "卧着的蚕，形容眉眼的形状。", defEn: "Lying silkworm (used to describe eyebrows)", defBm: "Ulat sutera berbaring (merujuk kepada bentuk kening)", example: "他长着一双卧蚕眉，看起来英气逼人。" },
    { word: "吸引", pinyin: "xī yǐn", defZh: "把事物引过来，引起注意或喜欢。", defEn: "Attract", defBm: "Menarik (perhatian)", example: "他的英勇事迹吸引了无数人的关注。" },
    { word: "乡兵", pinyin: "xiāng bīng", defZh: "由地方百姓组成的士兵队伍。", defEn: "Local militia", defBm: "Askar kampung", example: "他组织乡兵，保卫家乡免受侵扰。" },
    { word: "想法", pinyin: "xiǎng fǎ", defZh: "思考后的意见或打算。", defEn: "Idea / Thought", defBm: "Fikiran / Idea", example: "他有一个大胆的想法，但需要朋友的支持。" },
    { word: "相貌堂堂", pinyin: "xiàng mào táng táng", defZh: "形容人的外表端正、威严、有气度。", defEn: "Dignified appearance", defBm: "Rupa paras yang tampan dan gagah", example: "他相貌堂堂，器宇轩昂，一看就不是普通人。" },
    { word: "性情", pinyin: "xìng qíng", defZh: "人的性格、脾气。", defEn: "Disposition / Temperament", defBm: "Perangai / Sifat", example: "他性情豪爽，喜欢结交四方朋友。" },
    { word: "兄弟", pinyin: "xiōng dì", defZh: "哥哥和弟弟，也指朋友间亲密的关系。", defEn: "Brothers", defBm: "Adik-beradik lelaki", example: "他们虽然是异姓兄弟，但情同手足。" },
    { word: "胸怀大志", pinyin: "xiōng huái dà zhì", defZh: "心中怀有远大的志向和抱负。", defEn: "Have high aspirations", defBm: "Mempunyai cita-cita tinggi", example: "他虽出身贫寒，但胸怀大志，不甘平庸。" },
    { word: "言语", pinyin: "yán yǔ", defZh: "说的话、语言表达。", defEn: "Speech / Words", defBm: "Kata-kata", example: "他言语诚恳，让人感到信任。" },
    { word: "一事无成", pinyin: "yí shì wú chéng", defZh: "什么事情都没做成，毫无成就。", defEn: "Achieve nothing", defBm: "Tidak mencapai apa-apa kejayaan", example: "他感叹自己年过半百，却一事无成。" },
    { word: "异于一般", pinyin: "yì yú yì bān", defZh: "和普通人或普通事物不同。", defEn: "Out of the ordinary", defBm: "Luar biasa / Berbeza daripada biasa", example: "他的才华异于一般，令人刮目相看。" },
    { word: "应征", pinyin: "yìng zhēng", defZh: "响应招募，报名参加。", defEn: "Respond to a call for recruits", defBm: "Menyahut seruan (untuk menyertai tentera)", example: "他应征入伍，成为了一名勇敢的士兵。" },
    { word: "犹如", pinyin: "yóu rú", defZh: "好像、如同。", defEn: "Like / As if", defBm: "Bagaikan / Seperti", example: "他的眼神犹如利剑，令人不敢直视。" },
    { word: "赞同", pinyin: "zàn tóng", defZh: "同意、赞成别人的意见或主张。", defEn: "Agree / Approve", defBm: "Bersetuju", example: "大家一致赞同他的提议，决定共同行动。" },
    { word: "造反", pinyin: "zào fǎn", defZh: "发动叛乱，反抗朝廷的统治。", defEn: "Rebel / Revolt", defBm: "Memberontak", example: "由于苛政，百姓被迫起来造反。" },
    { word: "贼将", pinyin: "zéi jiàng", defZh: "敌军或叛军的将领。", defEn: "Enemy general / Rebel leader", defBm: "Jeneral musuh", example: "他勇猛无比，一枪刺死了贼将。" },
    { word: "赠送", pinyin: "zèng sòng", defZh: "把东西无偿地送给别人。", defEn: "Give as a present", defBm: "Memberi hadiah", example: "朋友之间互相赠送礼物，以表心意。" },
    { word: "战功", pinyin: "zhàn gōng", defZh: "在战争中建立的功劳。", defEn: "Military exploit", defBm: "Kejayaan dalam peperangan", example: "他因战功显赫，被晋升为大将军。" },
    { word: "招收", pinyin: "zhāo shōu", defZh: "通过招募吸收人员（如士兵、学生）。", defEn: "Recruit / Take in", defBm: "Mengambil (pekerja/askar) / Merekrut", example: "他奉朝廷之命，招收新兵以扩充军队。" },
    { word: "征讨", pinyin: "zhēng tǎo", defZh: "出兵讨伐、平定叛乱或敌人。", defEn: "Go on a punitive expedition", defBm: "Melancarkan kempen ketenteraan", example: "皇帝命他率兵征讨叛乱的地方势力。" },
    { word: "织席", pinyin: "zhī xí", defZh: "编织草席或竹席。", defEn: "Weave mats", defBm: "Menganyam tikar", example: "他年轻时家境贫寒，以织席为生。" },
    { word: "治病解危", pinyin: "zhì bìng jiě wēi", defZh: "治疗疾病，解决危难。", defEn: "Cure diseases and relieve crises", defBm: "Menyembuhkan penyakit dan menyelesaikan krisis", example: "他立志行医，治病解危，造福百姓。" },
    { word: "重要", pinyin: "zhòng yào", defZh: "意义重大，影响深远的。", defEn: "Important", defBm: "Penting", example: "这个决定非常重要，关系到国家的命运。" },
    { word: "著名", pinyin: "zhù míng", defZh: "有名气的、大家都知道的。", defEn: "Famous", defBm: "Terkenal", example: "这座古城以历史遗迹众多而著名。" },
    { word: "注意", pinyin: "zhù yì", defZh: "把心思集中到某件事上。", defEn: "Pay attention to", defBm: "Memberi perhatian", example: "行兵打仗时，必须注意观察敌情。" },
    { word: "转变", pinyin: "zhuǎn biàn", defZh: "事物发生改变，从一种状态变成另一种。", defEn: "Change / Transformation", defBm: "Perubahan", example: "他的思想发生了转变，决定投笔从戎。" },
    { word: "仔细", pinyin: "zǐ xì", defZh: "做事认真细致，不马虎。", defEn: "Careful / Detailed", defBm: "Teliti", example: "他仔细地观察地形，制定了周密的作战计划。" },
    { word: "宗室", pinyin: "zōng shì", defZh: "皇室的家族成员。", defEn: "Royal family / Clansmen", defBm: "Kerabat diraja", example: "他是汉朝宗室，对朝政有着深厚的情感。" },
    { word: "作战", pinyin: "zuò zhàn", defZh: "进行战斗、打仗。", defEn: "Fight / Go to war", defBm: "Berperang", example: "他亲临前线，指挥军队作战。" }
];

// 将数据暴露为全局变量
var allIdioms = vocabularyData;
